# Redirect with a 301
[[redirects]]
from = "/*"
to = "/index.html"
status = 301

# Redirect with a 302
[[redirects]]
from = "/*"
to = "/index.html"
status = 302

# Show a custom 404 for this path
[[redirects]]
from = "/*"
to = "/index.html"
status = 404

# Rewrite a path
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

