import { Icon } from '@iconify/react';
import { Grid, Typography } from '@mui/material';
import subscriptionsList from "../../../../../components/json/subscriptionList.json";

const DescriptionFormat = () => {
  return (
    <Grid container>
    <Grid
      display={"flex"}
      flexDirection={"column"}
      alignItems={"center"}
      alignSelf={"stretch"}
      justifyContent={"flex-start"}
      height={"20rem"}
      gap={2}
      item
      xs={3}
    >
      <Grid
        textAlign={"left"}
        display={"flex"}
        justifyContent={"flex-start"}
        alignItems={"center"}
        width={"100%"}
        item
        xs={12}
      >
        <Typography
          textAlign={"left"}
          fontSize={"14px"}
          fontWeight={400}
          fontFamily={"Inter"}
        >
          Overview
        </Typography>
      </Grid>
      <Grid
        textAlign={"left"}
        display={"flex"}
        justifyContent={"flex-start"}
        alignItems={"center"}
        width={"100%"}
        item
        xs={12}
      >
        <Typography
          textAlign={"left"}
          fontSize={"14px"}
          fontWeight={400}
          fontFamily={"Inter"}
        >
          Basic features
        </Typography>
      </Grid>
      <Grid
        textAlign={"left"}
        display={"flex"}
        justifyContent={"flex-start"}
        alignItems={"center"}
        width={"100%"}
        item
        xs={12}
      >
        <Typography
          textAlign={"left"}
          fontSize={"14px"}
          fontWeight={400}
          fontFamily={"Inter"}
        >
          Admin users
        </Typography>
      </Grid>
      <Grid
        textAlign={"left"}
        display={"flex"}
        justifyContent={"flex-start"}
        alignItems={"center"}
        width={"100%"}
        item
        xs={12}
      >
        <Typography
          textAlign={"left"}
          fontSize={"14px"}
          fontWeight={400}
          fontFamily={"Inter"}
        >
          Support
        </Typography>
      </Grid>
      <Grid
        textAlign={"left"}
        display={"flex"}
        justifyContent={"flex-start"}
        alignItems={"center"}
        width={"100%"}
        item
        xs={12}
      >
        <Typography
          textAlign={"left"}
          fontSize={"14px"}
          fontWeight={400}
          fontFamily={"Inter"}
        >
          Remote support
        </Typography>
      </Grid>
      <Grid
        textAlign={"left"}
        display={"flex"}
        justifyContent={"flex-start"}
        alignItems={"center"}
        width={"100%"}
        item
        xs={12}
      >
        <Typography
          textAlign={"left"}
          fontSize={"14px"}
          fontWeight={400}
          fontFamily={"Inter"}
        >
          Merchant service
        </Typography>
      </Grid>
      <Grid
        textAlign={"left"}
        display={"flex"}
        justifyContent={"flex-start"}
        alignItems={"center"}
        width={"100%"}
        item
        xs={12}
      >
        <Typography
          textAlign={"left"}
          fontSize={"14px"}
          fontWeight={400}
          fontFamily={"Inter"}
        >
          Training videos
        </Typography>
      </Grid>
      <Grid
        textAlign={"left"}
        display={"flex"}
        justifyContent={"flex-start"}
        alignItems={"center"}
        width={"100%"}
        item
        xs={12}
      >
        <Typography
          textAlign={"left"}
          fontSize={"14px"}
          fontWeight={400}
          fontFamily={"Inter"}
        >
          Data history
        </Typography>
      </Grid>
    </Grid>
    <Grid
      display={"flex"}
      alignItems={"center"}
      justifyContent={"space-between"}
      height={"20rem"}
      gap={5}
      item
      xs={9}
    >
      {subscriptionsList.subscriptionsList.map((option, index) => {
        return (
          <Grid
            key={`grid-subscription-${option.id}`}
            display={"flex"}
            flexDirection={"column"}
            alignItems={"center"}
            alignSelf={"stretch"}
            justifyContent={"flex-start"}
            height={"20rem"}
            gap={2}
            item
            xs={3}
          >
            <Grid
              textAlign={"left"}
              display={"flex"}
              justifyContent={"flex-start"}
              alignItems={"center"}
              width={"100%"}
              item
              xs={12}
            >
              <Typography
                textAlign={"left"}
                fontSize={"14px"}
                fontWeight={400}
                fontFamily={"Inter"}
                color={"transparent"}
              ></Typography>
            </Grid>
            <Grid
              textAlign={"center"}
              display={"flex"}
              justifyContent={"center"}
              alignItems={"center"}
              width={"100%"}
              item
              xs={12}
            >
              <Typography
                textAlign={"center"}
                fontSize={"14px"}
                fontWeight={400}
                fontFamily={"Inter"}
              >
                <Icon
                  icon="ph:check-circle"
                  color="green"
                  width={20}
                  height={20}
                />
              </Typography>
            </Grid>
            <Grid
              textAlign={"center"}
              display={"flex"}
              justifyContent={"center"}
              alignItems={"center"}
              width={"100%"}
              item
              xs={12}
            >
              <Typography
                textAlign={"center"}
                fontSize={"14px"}
                fontWeight={400}
                fontFamily={"Inter"}
              >
                {option.adminUser}
              </Typography>
            </Grid>
            <Grid
              textAlign={"center"}
              display={"flex"}
              justifyContent={"center"}
              alignItems={"center"}
              width={"100%"}
              item
              xs={12}
            >
              <Typography
                textAlign={"center"}
                fontSize={"14px"}
                fontWeight={400}
                fontFamily={"Inter"}
                color={"transparent"}
              ></Typography>
            </Grid>
            <Grid
              textAlign={"center"}
              display={"flex"}
              justifyContent={"center"}
              alignItems={"center"}
              width={"100%"}
              item
              xs={12}
            >
              <Typography
                textAlign={"center"}
                fontSize={"14px"}
                fontWeight={400}
                fontFamily={"Inter"}
              >
                {option.support ? (
                  <Icon
                    icon="ph:check-circle"
                    color="green"
                    width={20}
                    height={20}
                  />
                ) : (
                  <Icon icon="pajamas:dash" width={20} height={20} />
                )}
              </Typography>
            </Grid>
            <Grid
              textAlign={"center"}
              display={"flex"}
              justifyContent={"center"}
              alignItems={"center"}
              width={"100%"}
              item
              xs={12}
            >
              <Typography
                textAlign={"center"}
                fontSize={"14px"}
                fontWeight={400}
                fontFamily={"Inter"}
              >
                {option.merchantService ? (
                  <Icon
                    icon="ph:check-circle"
                    color="green"
                    width={20}
                    height={20}
                  />
                ) : (
                  <Icon icon="pajamas:dash" width={20} height={20} />
                )}
              </Typography>
            </Grid>
            <Grid
              textAlign={"center"}
              display={"flex"}
              justifyContent={"center"}
              alignItems={"center"}
              width={"100%"}
              item
              xs={12}
            >
              <Typography
                textAlign={"center"}
                fontSize={"14px"}
                fontWeight={400}
                fontFamily={"Inter"}
              >
                {option.training ? (
                  <Icon
                    icon="ph:check-circle"
                    color="green"
                    width={20}
                    height={20}
                  />
                ) : (
                  <Icon icon="pajamas:dash" width={20} height={20} />
                )}
              </Typography>
            </Grid>
            <Grid
              textAlign={"center"}
              display={"flex"}
              justifyContent={"center"}
              alignItems={"center"}
              width={"100%"}
              item
              xs={12}
            >
              <Typography
                textAlign={"center"}
                fontSize={"14px"}
                fontWeight={400}
                fontFamily={"Inter"}
              >
                {option.dataHistory ? (
                  <Icon
                    icon="ph:check-circle"
                    color="green"
                    width={20}
                    height={20}
                  />
                ) : (
                  <Icon icon="pajamas:dash" width={20} height={20} />
                )}
              </Typography>
            </Grid>
          </Grid>
        );
      })}
    </Grid>
  </Grid>
  )
}

export default DescriptionFormat