const editItemFields = ({
    allSerialNumbersOptions,
    displayContainerSplotLimitField,
    displayPreviewImage,
    displaySublocationFields,
    isRented,
    options,
    OutlinedInputStyle,
    renderLocationOptions,
    retrieveItemOptions,
    subLocationsOptions,
  }) => {
    const fields = [
      {
        name: "item_group",
        placeholder: "Type the name of the item",
        label: "Item name",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: retrieveItemOptions("item_group"),
        htmlOption: 0,
        tooltip: false,
        tooltipMessage: null,
        displayField: true,
      },
      {
        name: "category_name",
        placeholder: "e.g. Electronic",
        label: "Category",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: retrieveItemOptions("category_name"),
        htmlOption: 0,
        tooltip: false,
        tooltipMessage: null,
        displayField: true,
      },
      {
        name: "brand",
        placeholder: "e.g. Apple",
        label: "Brand",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: retrieveItemOptions("brand"),
        htmlOption: 0,
        tooltip: false,
        tooltipMessage: null,
        displayField: true,
      },
      {
        name: "cost",
        placeholder: "e.g. 12000.54 | 95.44 | 4585",
        label: "Replacement cost",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: retrieveItemOptions("cost"),
        htmlOption: 0,
        tooltip: false,
        tooltipMessage: null,
        displayField: true,
      },
      {
        name: "tax_location",
        placeholder: "e.g. 12000.54 | 95.44 | 4585",
        label: "Taxable location",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: renderLocationOptions(),
        htmlOption: 2,
        tooltip: true,
        tooltipMessage:
          "Address where tax deduction for equipment will be applied.",
        displayField: true,
      },
      {
        name: "container",
        placeholder: "e.g. Permanent",
        label: "Is it a container?",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: [
          {
            value: "No - It is not a container",
          },
          {
            value: "Yes - It is a container",
          },
        ],
        htmlOption: 2,
        tooltip: true,
        tooltipMessage: "This item will contain other items inside.",
        displayField: true,
      },
      {
        name: "containerSpotLimit",
        placeholder: "e.g. 120 | 250 | 500",
        label: "Container Spot Limit",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: [],
        htmlOption: 2,
        tooltip: true,
        tooltipMessage: "How many items can be stored inside the container.",
        displayedButton: false,
        displayField: displayContainerSplotLimitField,
      },
      {
        name: "location",
        placeholder: "Select a location",
        label: "Main location",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: renderLocationOptions(),
        htmlOption: 2,
        tooltip: true,
        tooltipMessage: "Where the item is location physically.",
        displayField: true,
      },
      {
        name: "sub_location",
        placeholder: "Select or type a sub location",
        label: "Sub location",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: subLocationsOptions,
        htmlOption: 2,
        tooltip: true,
        tooltipMessage: "Where the item is location physically.",
        displayField: displaySublocationFields,
      },
      {
        name: "serial_number",
        placeholder: "e.g. 300",
        label: "Serial number",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: allSerialNumbersOptions,
        htmlOption: 0,
        tooltip: false,
        tooltipMessage: null,
        displayField: true,
      },
      {
        name: "ownership",
        placeholder: "e.g. Permanent",
        label: "Ownership status of item",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: options,
        htmlOption: 2,
        tooltip: true,
        tooltipMessage: "Date when the leased equipment will be returned.",
        displayField: true,
      },
      {
        name: "",
        placeholder: "",
        label: "Returning date",
        htmlElement: "Day",
        style: OutlinedInputStyle,
        required: true,
        options: options,
        htmlOption: 2,
        tooltip: true,
        tooltipMessage: "Date when the leased equipment will be returned.",
        displayField: isRented,
      },
      {
        name: "enableAssignFeature",
        placeholder: "",
        label: "Is it assignable to staff/events?",
        htmlElement: "",
        style: OutlinedInputStyle,
        required: true,
        options: ["Enabled", "Disabled"],
        htmlOption: 0,
        tooltip: true,
        tooltipMessage: "Select if the device is assignable to staff or events.",
        displayField: true,
      },
      {
        name: "image_uploader",
        placeholder: "",
        label: "Image uploader",
        htmlElement: "Day",
        style: OutlinedInputStyle,
        required: true,
        options: [],
        htmlOption: 6,
        tooltip: false,
        tooltipMessage: null,
        displayField: true,
      },
      {
        name: "image_uploader_preview",
        placeholder: "",
        label: "Preview image uploader",
        htmlElement: "ImagePreview",
        style: OutlinedInputStyle,
        required: true,
        options: [],
        htmlOption: 6,
        tooltip: false,
        tooltipMessage: null,
        displayField: displayPreviewImage
      },
      {
        name: "descript_item",
        placeholder:
          "Please provide a brief description of the new device to be added.",
        label: "Description of the device",
        htmlElement: "TextArea",
        style: OutlinedInputStyle,
        required: true,
        options: options,
        htmlOption: 4,
        tooltip: true,
        tooltipMessage: "Date when the leased equipment will be returned.",
        displayField: true,
      },
      {
        name: "image_url",
        placeholder: "",
        label: "Image uploader",
        htmlElement: "Day",
        style: OutlinedInputStyle,
        required: true,
        options: [],
        htmlOption: 6,
        tooltip: false,
        tooltipMessage: null,
        displayField: false,
      }
    ];
  
    fields.forEach((_, index) => {
      fields[index].id = fields[index].name;
    });
    return fields;
  };
  
  export default editItemFields