const editItemFields = ({
  displayContainerSplotLimitField,
  displayPreviewImage,
  isRented,
  options,
  OutlinedInputStyle,
  renderLocationOptions,
  retrieveItemOptions,
  subLocationsOptions,
  suppliersOptions,
}) => {
  const fields = [
    {
      name: "item_group",
      placeholder: "Type the name of the item",
      label: "Item name",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: retrieveItemOptions("item_group"),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "category_name",
      placeholder: "Select or type category of device",
      label: "Category of device",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: retrieveItemOptions("category_name"),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "brand",
      placeholder: "Select or type brand of device",
      label: "Brand of device",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: retrieveItemOptions("brand"),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "cost",
      placeholder: "Select or type replacement cost of device",
      label: "Replacement cost of device",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: retrieveItemOptions("cost"),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "container",
      placeholder: "Select container option",
      label: "Is device a container?",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: [
        { value: "No - It is not a container" },
        { value: "Yes - It is a container" },
      ],
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "This item will contain other items inside.",
      displayField: true,
      children: [
        {
          name: "containerSpotLimit",
          placeholder: "e.g. 120 | 250 | 500",
          label: "Is this carrying/storage units?",
          htmlElement: "",
          style: OutlinedInputStyle,
          required: true,
          options: [],
          htmlOption: 0,
          tooltip: true,
          tooltipMessage: "How many items can be stored inside the container.",
          displayedButton: false,
          displayField: displayContainerSplotLimitField,
        },
      ],
    },
    {
      name: "ownership",
      placeholder: "Select ownership option",
      label: "Ownership status of device",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: options,
      htmlOption: 2,
      tooltip: true,
      tooltipMessage:
        "Device ownership. If device is a rental device, return date field will be prompted.",
      displayField: true,
      children: [
        {
          name: "",
          placeholder: "",
          label: "Returning date of device",
          htmlElement: "Day",
          style: OutlinedInputStyle,
          required: true,
          options: options,
          htmlOption: 2,
          tooltip: true,
          tooltipMessage: "Date when the leased equipment will be returned.",
          displayField: isRented,
        },
        {
          name: "supplier",
          placeholder: "Select a supplier",
          label: "Supplier of device",
          htmlElement: "",
          style: OutlinedInputStyle,
          required: true,
          options: suppliersOptions,
          htmlOption: 0,
          tooltip: true,
          tooltipMessage: "Supplier where rented equipment will be returned.",
          displayField: isRented,
        },
      ],
    },
    {
      name: "enableAssignFeature",
      placeholder: "Select assign option",
      label: "Is device assignable to staff/events?",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: ["YES", "NO"],
      htmlOption: 0,
      tooltip: true,
      tooltipMessage: "Select if the device is assignable to staff or events.",
      displayField: true,
    },
    {
      name: "tax_location",
      placeholder: "e.g. 12000.54 | 95.44 | 4585",
      label: "Taxable location",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: renderLocationOptions(),
      htmlOption: 2,
      tooltip: true,
      tooltipMessage:
        "Address where tax deduction for equipment will be applied.",
      displayField: true,
    },
    {
      name: "location",
      placeholder: "Select a location",
      label: "Main location",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: renderLocationOptions(),
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "Where the item is location physically.",
      displayField: true,
    },
    {
      name: "sub_location",
      placeholder: "Select or type a sub location",
      label: "Sub location",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: false,
      options: subLocationsOptions,
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "Where the item is location physically.",
      displayField: true,
    },
    {
      name: "image_uploader",
      placeholder: "",
      label: "Image uploader",
      htmlElement: "Day",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 6,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "image_uploader_preview",
      placeholder: "",
      label: "Preview image uploader",
      htmlElement: "ImagePreview",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 6,
      tooltip: false,
      tooltipMessage: null,
      displayField: displayPreviewImage,
    },
    {
      name: "descript_item",
      placeholder: "Please provide a brief description of the device.",
      label: "Description of the device",
      htmlElement: "TextArea",
      style: OutlinedInputStyle,
      required: true,
      options: options,
      htmlOption: 4,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "image_url",
      placeholder: "",
      label: "Image uploader",
      htmlElement: "Day",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 6,
      tooltip: false,
      tooltipMessage: null,
      displayField: false,
    },
  ];

  fields.forEach((_, index) => {
    fields[index].id = fields[index].name;
  });
  return fields;
};

export default editItemFields;
