export const renderFields = ({
  // addSerialNumberField,
  // allSerialNumbersOptions,
  displayContainerSplotLimitField,
  displayPreviewImage,
  // displaySublocationFields,
  isRented,
  // labeling,
  options,
  OutlinedInputStyle,
  // rangeFormat,
  renderLocationOptions,
  retrieveItemOptions,
  subLocationsOptions,
  suppliersOptions,
  // isLoadingLocations,
  // isLocationSetupAllowed,
}) => {
  const normalizeOptions = (opts) => {
    if (!Array.isArray(opts)) return [];
    return opts.map((opt) =>
      typeof opt === "string"
        ? { value: opt, label: opt }
        : { ...opt, label: opt.label || opt.value }
    );
  };

  // The four "reference_*" fields that used to open this list live in
  // CopyFromExistingDevicePanel now. They were optional shortcuts for
  // pre-filling the form, but sitting here they rendered with the same weight
  // as the fields that define the item — bold and underlined, no less — so
  // users read them as four more mandatory inputs and filled them in as if
  // they were part of the record. The panel gives them a border, a title that
  // says what they do, and a note that they are optional.
  const fields = [
    {
      name: "item_group",
      placeholder: "Type the name of the item",
      label: "Group",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(retrieveItemOptions("item_group")),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "category_name",
      placeholder: "Select or type category",
      label: "Category",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(retrieveItemOptions("category_name")),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "brand",
      placeholder: "Select or type brand",
      label: "Brand",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(retrieveItemOptions("brand")),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "cost",
      placeholder: "Select or type replacement cost",
      label: "Replacement cost",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(retrieveItemOptions("cost")),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "tax_location",
      placeholder: "e.g. 12000.54 | 95.44 | 4585",
      label: "Taxable location",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: renderLocationOptions("tax_location"),
      htmlOption: 2,
      tooltip: true,
      tooltipMessage:
        "Address where tax deduction for equipment will be applied.",
      displayField: true,
    },
    {
      name: "location",
      placeholder: "Select a location",
      label: "Main location",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: renderLocationOptions(),
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "Where the item is location physically.",
      displayField: true,
    },
    {
      name: "sub_location",
      placeholder: "Select or type a sub location",
      label: "Sub location",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: false,
      options: subLocationsOptions,
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "Where the item is location physically.",
      displayField: true //displaySublocationFields,
    },
        {
      name: "container",
      placeholder: "Select container option",
      label: "Is this carrying/storage units?",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: [
        {
          value: "No",
          label: "No - It is not a container",
        },
        {
          value: "Yes",
          label: "Yes - It is a container",
        },
      ],
      htmlOption: 3,
      tooltip: true,
      tooltipMessage: "This item will contain other items inside.",
      displayField: true,
      children: [
        {
          name: "containerSpotLimit",
          placeholder: "e.g. 120 | 250 | 500",
          label: "Container Spot Limit",
          htmlElement: "",
          style: OutlinedInputStyle,
          required: true,
          options: [],
          htmlOption: 0,
          tooltip: true,
          tooltipMessage: "How many items can be stored inside the container.",
          displayedButton: false,
          displayField: displayContainerSplotLimitField,
        },
      ],
    },
    {
      name: "containerSpotLimit",
      placeholder: "e.g. 120 | 250 | 500",
      label: "Container Spot Limit",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 0,
      tooltip: true,
      tooltipMessage: "How many items can be stored inside the container.",
      displayedButton: false,
      displayField: displayContainerSplotLimitField,
    },
    {
      name: "ownership",
      placeholder: "Select ownership option",
      label: "Ownership status",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(options),
      htmlOption: 3,
      tooltip: true,
      tooltipMessage: "Device ownership. If device is a rental device, return date field will be prompted.",
      displayField: true,
      children: [
        {
          name: "",
          placeholder: "",
          label: "Returning date",
          htmlElement: "Day",
          style: OutlinedInputStyle,
          required: true,
          options: options,
          htmlOption: 2,
          tooltip: true,
          tooltipMessage: "Date when the leased equipment will be returned.",
          displayField: isRented,
        },
        {
          name: "supplier",
          placeholder: "Select a supplier",
          label: "Supplier",
          htmlElement: "",
          style: OutlinedInputStyle,
          required: true,
          options: suppliersOptions,
          htmlOption: 0,
          tooltip: true,
          tooltipMessage: "Supplier where rented equipment will be returned.",
          displayField: isRented,
        },
      ],
    },
    {
      name: "",
      placeholder: "",
      label: "Returning date",
      htmlElement: "Day",
      style: OutlinedInputStyle,
      required: true,
      options: options,
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "Date when the leased equipment will be returned.",
      displayField: isRented,
    },
    {
      name: "supplier",
      placeholder: "Select a supplier",
      label: "Supplier",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: suppliersOptions,
      htmlOption: 0,
      tooltip: true,
      tooltipMessage: "Supplier where rented equipment will be returned.",
      displayField: isRented,
    },
    {
      name: "enableAssignFeature",
      placeholder: "Select assign option",
      label: "Is device assignable to staff/events?",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(["YES", "NO"]),
      htmlOption: 3,
      tooltip: true,
      tooltipMessage: "Select if the device is assignable to staff or events.",
      displayField: true,
    },

    {
      name: "image_uploader",
      placeholder: "",
      label: "Image uploader",
      htmlElement: "Day",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 6,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "image_uploader_preview",
      placeholder: "",
      label: "Preview image uploader",
      htmlElement: "ImagePreview",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 6,
      tooltip: false,
      tooltipMessage: null,
      displayField: displayPreviewImage,
    },
    {
      name: "image_url",
      placeholder: "",
      label: "Image uploader",
      htmlElement: "Day",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 6,
      tooltip: false,
      tooltipMessage: null,
      displayField: false,
    },
  ];

  fields.forEach((_, index) => {
    fields[index].id = fields[index].name;
  });
  return fields;
};
