export const renderFields = ({
  addSerialNumberField,
  allSerialNumbersOptions,
  displayContainerSplotLimitField,
  displayPreviewImage,
  displaySublocationFields,
  isRented,
  labeling,
  options,
  OutlinedInputStyle,
  rangeFormat,
  renderLocationOptions,
  retrieveItemOptions,
  subLocationsOptions,
  suppliersOptions,
  // isLoadingLocations,
  // isLocationSetupAllowed,
}) => {
  const normalizeOptions = (opts) => {
    if (!Array.isArray(opts)) return [];
    return opts.map((opt) => (typeof opt === "string" ? { value: opt } : opt));
  };

  const fields = [
    {
      name: "reference_category_name",
      placeholder: "e.g. Electronic",
      label: "Category reference",
      htmlElement: "",
      style: {
        ...OutlinedInputStyle,
        textDecoration: "underline",
        fontWeight: 700,
      },
      required: false,
      options: normalizeOptions(retrieveItemOptions("category_name")),
      htmlOption: 0,
      tooltip: true,
      tooltipMessage: "This is the category of the reference item.",
      displayField: false,
    },
    {
      name: "reference_item_group",
      placeholder:
        "Type the name of the item for retrieving the reference item.",
      label: "Item name reference",
      htmlElement: "",
      style: {
        ...OutlinedInputStyle,
        textDecoration: "underline",
        fontWeight: 700,
      },
      required: false,
      options: normalizeOptions(retrieveItemOptions("item_group")),
      htmlOption: 0,
      tooltip: true,
      tooltipMessage: "This is the item group of the reference item.",
      displayField: true,
    },
    {
      name: "item_group",
      placeholder: "Type the name of the item",
      label: "Item name",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(retrieveItemOptions("item_group")),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "category_name",
      placeholder: "e.g. Electronic",
      label: "Category",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(retrieveItemOptions("category_name")),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "brand",
      placeholder: "e.g. Apple",
      label: "Brand",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(retrieveItemOptions("brand")),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "cost",
      placeholder: "e.g. 12000.54 | 95.44 | 4585",
      label: "Replacement cost",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(retrieveItemOptions("cost")),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "tax_location",
      placeholder: "e.g. 12000.54 | 95.44 | 4585",
      label: "Taxable location",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: renderLocationOptions("tax_location"),
      htmlOption: 2,
      tooltip: true,
      tooltipMessage:
        "Address where tax deduction for equipment will be applied.",
      displayField: true,
    },
    {
      name: "container",
      placeholder: "e.g. Permanent",
      label: "Is it a container?",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: [
        {
          value: "No - It is not a container",
        },
        {
          value: "Yes - It is a container",
        },
      ],
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "This item will contain other items inside.",
      displayField: true,
    },
    {
      name: "containerSpotLimit",
      placeholder: "e.g. 120 | 250 | 500",
      label: "Container Spot Limit",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "How many items can be stored inside the container.",
      displayedButton: false,
      displayField: displayContainerSplotLimitField,
    },
    {
      name: "location",
      placeholder: "Select a location",
      label: "Main location",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: renderLocationOptions(),
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "Where the item is location physically.",
      displayField: true,
    },
    {
      name: "sub_location",
      placeholder: "Select or type a sub location",
      label: "Sub location",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: false,
      options: subLocationsOptions,
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "Where the item is location physically.",
      displayField: displaySublocationFields,
    },
    {
      name: "format_range_serial_number",
      placeholder: "e.g. SKJDD6564H, SKJDD6564J | 542101-542110",
      label: "Serial number range format",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(["Custom format", "Sequential number"]),
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "feed_serial_number",
      placeholder: "e.g. typing one by one or scanning multiple serial numbers",
      label: "How serial number will be submitted",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: normalizeOptions(["Typing", "Scanning"]),
      htmlOption: 0,
      tooltip: true,
      tooltipMessage:
        "Typing option: typing one by one if format is custom, typing starting/ending serial number if format is sequential number. Scanning option: scanning multiple serial numbers.",
      displayField: true,
    },
    {
      name: "serial_number_list",
      placeholder: "e.g. 300",
      label: labeling,
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: allSerialNumbersOptions,
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: rangeFormat,
    },
    {
      name: "quantity",
      placeholder: "e.g. 300",
      label: "Quantity",
      htmlElement: "Quantity",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 0,
      tooltip: false,
      tooltipMessage:
        "This is the quantity from starting serial number and ending serial number.",
      displayField: true,
    },
    {
      name: "min_serial_number",
      placeholder: "e.g. 300",
      label: "Starting Serial number",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: allSerialNumbersOptions,
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: addSerialNumberField,
    },
    {
      name: "max_serial_number",
      placeholder: "e.g. 300",
      label: "Ending Serial number",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: allSerialNumbersOptions,
      htmlOption: 0,
      tooltip: false,
      tooltipMessage: null,
      displayField: addSerialNumberField,
    },
    {
      name: "ownership",
      placeholder: "e.g. Permanent",
      label: "Ownership status of item",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: options,
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "Date when the leased equipment will be returned.",
      displayField: true,
    },
    {
      name: "",
      placeholder: "",
      label: "Returning date",
      htmlElement: "Day",
      style: OutlinedInputStyle,
      required: true,
      options: options,
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "Date when the leased equipment will be returned.",
      displayField: isRented,
    },
    {
      name: "supplier",
      placeholder: "Select a supplier",
      label: "Supplier",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: suppliersOptions,
      htmlOption: 2,
      tooltip: true,
      tooltipMessage: "Supplier where rented equipment will be returned.",
      displayField: isRented,
    },
    {
      name: "enableAssignFeature",
      placeholder: "",
      label: "Is it assignable to staff/events?",
      htmlElement: "",
      style: OutlinedInputStyle,
      required: true,
      options: ["YES", "NO"],
      htmlOption: 0,
      tooltip: true,
      tooltipMessage: "Select if the device is assignable to staff or events.",
      displayField: true,
    },
    {
      name: "image_uploader",
      placeholder: "",
      label: "Image uploader",
      htmlElement: "Day",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 6,
      tooltip: false,
      tooltipMessage: null,
      displayField: true,
    },
    {
      name: "image_uploader_preview",
      placeholder: "",
      label: "Preview image uploader",
      htmlElement: "ImagePreview",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 6,
      tooltip: false,
      tooltipMessage: null,
      displayField: displayPreviewImage,
    },
    {
      name: "descript_item",
      placeholder:
        "Please provide a brief description of the new device to be added.",
      label: "Description of the device",
      htmlElement: "TextArea",
      style: OutlinedInputStyle,
      required: true,
      options: options,
      htmlOption: 4,
      tooltip: true,
      tooltipMessage: "Date when the leased equipment will be returned.",
      displayField: true,
    },
    {
      name: "image_url",
      placeholder: "",
      label: "Image uploader",
      htmlElement: "Day",
      style: OutlinedInputStyle,
      required: true,
      options: [],
      htmlOption: 6,
      tooltip: false,
      tooltipMessage: null,
      displayField: false,
    },
  ];

  fields.forEach((_, index) => {
    fields[index].id = fields[index].name;
  });
  return fields;
};